name: CI Pipeline - Frontend React Build & Smoke Test

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build Frontend
        run: npm run build

      - name: Start Frontend & Smoke Test
        run: |
          npm install -g serve
          serve -s dist -l 5173 &       
          sleep 5
          curl -f http://localhost:5173/ || exit 1
          kill $(jobs -p)
